### ISSUE TITLE
TODO: add a CI for all versions of TodoApp

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/workshops#45]
# CI for TodoApp

The goal is to avoid having non-working solutions for the workshop.

Requirements:
* [ ] It must use Azure Pipelines with a `azure-pipelines.yml` file.
* [ ] All solutions must build correctly (no need for artifacts)
* [ ] Optional: the resulting applications should be tested to work properly using UI Tests

A good example would be the one defined with Uado: <https://github.com/unoplatform/uado/blob/master/azure-pipelines.yml>

**Comment by gagandeepp** [comment]
Please provide details on this

**Comment by carldebilly** [comment]
Done
